<?php
/**
 * Nigeria States
 */
global $states;

$states['NG'] = array(
	'AB' => esc_html__( 'Abia', 'zoner' ),
	'AD' => esc_html__( 'Adamawa', 'zoner' ),
	'AK' => esc_html__( 'Akwa Ibom', 'zoner' ),
	'AN' => esc_html__( 'Anambra', 'zoner' ),
	'BA' => esc_html__( 'Bauchi', 'zoner' ),
	'BY' => esc_html__( 'Bayelsa', 'zoner' ),
	'BE' => esc_html__( 'Benue', 'zoner' ),
	'BO' => esc_html__( 'Borno', 'zoner' ),
	'CR' => esc_html__( 'Cross River', 'zoner' ),
	'DE' => esc_html__( 'Delta', 'zoner' ),
	'EB' => esc_html__( 'Ebonyi', 'zoner' ),
	'ED' => esc_html__( 'Edo', 'zoner' ),
	'EK' => esc_html__( 'Ekiti', 'zoner' ),
	'EN' => esc_html__( 'Enugu', 'zoner'),	
	'FC' => esc_html__( 'Federal Capital Territory', 'zoner'),	
	'GO' => esc_html__( 'Gombe', 'zoner' ),
	'IM' => esc_html__( 'Imo', 'zoner' ),
	'JI' => esc_html__( 'Jigawa', 'zoner' ),
	'KD' => esc_html__( 'Kaduna', 'zoner' ),
	'KN' => esc_html__( 'Kano', 'zoner' ),
	'KT' => esc_html__( 'Katsina', 'zoner' ),
	'KE' => esc_html__( 'Kebbi', 'zoner' ),
	'KO' => esc_html__( 'Kogi', 'zoner' ),
	'KW' => esc_html__( 'Kwara', 'zoner' ),
	'LA' => esc_html__( 'Lagos', 'zoner' ),
	'NA' => esc_html__( 'Nasarawa', 'zoner' ),
	'NI' => esc_html__( 'Niger', 'zoner' ),
	'OG' => esc_html__( 'Ogun', 'zoner' ),
	'ON' => esc_html__( 'Ondo', 'zoner' ),
	'OS' => esc_html__( 'Osun', 'zoner' ),
	'OY' => esc_html__( 'Oyo', 'zoner' ),
	'PL' => esc_html__( 'Plateau', 'zoner' ),
	'RI' => esc_html__( 'Rivers', 'zoner' ),
	'SO' => esc_html__( 'Sokoto', 'zoner' ),
	'TA' => esc_html__( 'Taraba', 'zoner' ),
	'YO' => esc_html__( 'Yobe', 'zoner' ),
	'ZA' => esc_html__( 'Zamfara', 'zoner' ),
);